name: bp-crud-react-node-mysql-go
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - bridge

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bridge
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot -e 'USE test;'"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - db_data:/var/lib/mysql
      - ./database_setup/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
    networks:
      - bridge
volumes:
  db_data:
networks:
  bridge:
    driver: bridge